// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBtmYFTajIgiIBe-eAAcrlfWM_p3pIiXg8',
//     appId: '1:307522958828:web:d530b424dfb841f6e33cc9',
//     messagingSenderId: '307522958828',
//     projectId: 'odev-feee8',
//     authDomain: 'odev-feee8.firebaseapp.com',
//     storageBucket: 'odev-feee8.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD2jbA62hvbW_JK7K2muFpIQp8pY5G4_q0',
//     appId: '1:307522958828:android:c4c6bfe927b92735e33cc9',
//     messagingSenderId: '307522958828',
//     projectId: 'odev-feee8',
//     storageBucket: 'odev-feee8.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBpZv6DbPnXrHSKTRNAcQ-WbBSufmaTnuA',
//     appId: '1:307522958828:ios:b0d31744f45ed788e33cc9',
//     messagingSenderId: '307522958828',
//     projectId: 'odev-feee8',
//     storageBucket: 'odev-feee8.appspot.com',
//     iosBundleId: 'com.example.proje',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBpZv6DbPnXrHSKTRNAcQ-WbBSufmaTnuA',
//     appId: '1:307522958828:ios:e1e47580f479e5fde33cc9',
//     messagingSenderId: '307522958828',
//     projectId: 'odev-feee8',
//     storageBucket: 'odev-feee8.appspot.com',
//     iosBundleId: 'com.example.proje.RunnerTests',
//   );
// }
